### PR TITLE
Add firefox and apple DoH

### PR DESCRIPTION
**Pull request by andersix**
Using this list for pihole, but it does not have Mozilla's, nor Apple's doh. FYI, I paid no attention to ordering when adding these. Cheers!

### CODE REVIEW

**Comment by T145** [comment]
Feel free to send these contributions here: https://github.com/T145/white-bear

Considering this project seems to be inactive.

**Comment by andersix** [comment]
I actually just removed use-application-dns.net from my commits since in the latest pi-hole version, the reply for this domain is hardcoded to an NXDOMAIN response, so it should not be sinkholed. Others are, however, valid adds, I think.
Did not resubmit PR, FYI.

**Comment by dougK44883** [comment]
Since this list isn't a pi-hole specific, please don't remove something just because "pi-hole has it covered"

**Comment by T145** [comment]
> > Feel free to send these contributions here: https://github.com/T145/white-bear
> > Considering this project seems to be inactive.
> 
> Not inactive, just need to validate the additions.

Being active on GitHub in other projects does not make this project active. It should not take but less than one minute to verify four domains:

```
$ dig use-application-dns.net

; <<>> DiG 9.18.1-1-Debian <<>> use-application-dns.net
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35484
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;use-application-dns.net.       IN      A

;; ANSWER SECTION:
use-application-dns.net. 464    IN      A       44.236.72.93
use-application-dns.net. 464    IN      A       44.236.48.31
use-application-dns.net. 464    IN      A       44.235.246.155

;; Query time: 24 msec
;; SERVER: -
;; WHEN: Wed May 25 -
;; MSG SIZE  rcvd: 100

$ dig mozilla.cloudflare-dns.com

; <<>> DiG 9.18.1-1-Debian <<>> mozilla.cloudflare-dns.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 29772
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;mozilla.cloudflare-dns.com.    IN      A

;; ANSWER SECTION:
mozilla.cloudflare-dns.com. 94  IN      A       104.16.249.249
mozilla.cloudflare-dns.com. 94  IN      A       104.16.248.249

;; Query time: 20 msec
;; SERVER: -
;; WHEN: Wed May 25 -
;; MSG SIZE  rcvd: 87

$ dig doh.dns.apple.com         

; <<>> DiG 9.18.1-1-Debian <<>> doh.dns.apple.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53120
;; flags: qr rd ra; QUERY: 1, ANSWER: 7, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;doh.dns.apple.com.             IN      A

;; ANSWER SECTION:
doh.dns.apple.com.      273     IN      CNAME   doh.dns.apple.com.v.aaplimg.com.
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       17.253.4.247
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       17.253.4.85
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       64.78.201.1
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       17.253.16.247
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       64.78.200.1
doh.dns.apple.com.v.aaplimg.com. 33 IN  A       17.253.4.119

;; Query time: 12 msec
;; SERVER: -
;; WHEN: Wed May 25 -
;; MSG SIZE  rcvd: 184

dig doh.dns.apple.com.v.aaplimg.com

; <<>> DiG 9.18.1-1-Debian <<>> doh.dns.apple.com.v.aaplimg.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 38239
;; flags: qr rd ra; QUERY: 1, ANSWER: 6, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;doh.dns.apple.com.v.aaplimg.com. IN    A

;; ANSWER SECTION:
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       17.253.4.119
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       64.78.200.1
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       17.253.16.247
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       64.78.201.1
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       17.253.4.85
doh.dns.apple.com.v.aaplimg.com. 12 IN  A       17.253.4.247

;; Query time: 4 msec
;; SERVER: -
;; WHEN: Wed May 25 -
;; MSG SIZE  rcvd: 156
```



> I actually just removed use-application-dns.net from my commits since in the latest pi-hole version, the reply for this domain is hardcoded to an NXDOMAIN response, so it should not be sinkholed. Others are, however, valid adds, I think. Changes pushed to my PR .

Each domain is active.



> Since this list isn't a pi-hole specific, please don't remove something just because "pi-hole has it covered"

Domains being online or offline is not something that's platform-specific.

**Comment by oneoffdallas** [comment]
You mean you don't just add domains because someone says so and they are resolvable via dig? ;-)

**Pull request merged**
